### ISSUE TITLE
Disable Focus Zoom / Holding right click

### ISSUE THREAD

**Issue by filipbasara** [TaktiCool/ArmaAtWar#280]
### Description:

Remove the ability to focus zoom in general, to further improve the realism aspect of the mod.

**Comment by litrax** [comment]
Would be great. So one needs a scope, DMR or sniper rifle to effectively shoot over distances > 400m.
But then there must be enough equipment (e.g. scopes) for a team so that they not all must fight with ironsights ;-)
Or, in terms of balancing, give Riflemans ironsights and RedDots and establish a new Class "Designated Marksman". That would be great. There is something similar in PR and also in Squad.

**Comment by jokoho48** [comment]
i am against removing it. this is one of the core features for ArmA and is required for long distance firefights.

**Comment by pwilkutowski** [comment]
Also against removing, as the FOV of a screen is not a geometrically correct FOV. Actually the zoomed in FOV is somewhere around the geometrically corectt FOV.

If needed i can elaborate on this later, but the basics idea comes form sim racing and applies o actually all gaming:

https://www.youtube.com/watch?v=4yYeiAHsdr0

**Comment by Hoegnison** [comment]
team agreed taht this not an unfair issue. it simulates the focus of the human eye.
