### ISSUE TITLE
Revive Dont Reset Animation if you heal someone

### ISSUE THREAD

**Issue by jokoho48** [TaktiCool/ArmaAtWar#375]

**Comment by jokoho48** [comment]
cant reproduce maybe a Super Anal bug.

**Comment by litrax** [comment]
How can it be tested when the tag "can't reproduce" is set. Any idea?
We need more documentation of bugs. Cause I don't know what this bug is all about any more.
Isn't there an issue? How did the bug happen?

Maybe make some standard-test scenarios today or tomorrow. When they are passed, it's done?

**Comment by litrax** [comment]
Never been seen again.
