### ISSUE TITLE
Rally point spawn always on the ground

### ISSUE THREAD

**Issue by netfusion** [TaktiCool/ArmaAtWar#443]
When you place a RP as squad leader on a tower or upper floor of a building, the RP will always spawn on the ground.

**Comment by Krzmbrzl** [comment]
In my opinion the problem lays right here: https://github.com/TaktiCool/ArmaAtWar/blob/master/serverAddons/AAW/addons/AAW_Server/Rally/fn_place.sqf#L32

The z-component of all objects that are part of the rally point is only the terrain height at that point instead of the terrain height plus the player's height...

**Comment by jokoho48** [comment]
https://github.com/TaktiCool/ArmaAtWar/blob/SimpleObjectRally/serverAddons/PRA3/addons/PRA3_Server/Rally/fn_place.sqf i think SimpleObjectRally could fix this issue. but i think netfusion maybe want to dont allow it to place it in buildings. so maybe also a gamedesign thing to talk about

**Comment by jokoho48** [comment]
fixed by @simon84
