### ISSUE TITLE
Build new missions

### ISSUE THREAD

**Issue by Ribbonius** [TaktiCool/ArmaAtWar#559]
Build new infantry layouts.
Necessary for more diversion while the servers are not getting populated.

Ideas:

- Stratis
       (Around Mike26)

- Altis
       (in Kavalla; in Pyrgos; around the GhostHotel)

**Comment by Hoegnison** [comment]
2 missions are done and ready for the first qa. (Op. Artemis and Ares) Maybe I will do some alternative layouts or another inf mission, but not sure if I can manage this in this sprint-

**Comment by litrax** [comment]
Just could test the layout and assets, not the gameplay mechanic!
OP Artemis: The Refuel-Container of AAF must be placed on even ground or it is destroyed.
OP Ares: Just two little "bugs" in the city: 
+ Smoke-source is placed in the middle of a door instead of the ruin of that's on that house.
+ One can bug a litte bit on the balkony of the house directed NW (towards Nato Base) cause of the sandbags. Is probably just the normal Arma balkony bug. ;)

Strategically I find OP Artemis very interesting. Looking forward to play this.

Let's close the issue when having played the missions with a few guys...

**Comment by litrax** [comment]
@Hoegnison I think this issue can be closed, if the playtest was succesfull!?

**Comment by jokoho48** [comment]
I think that should be an ongoing issue until we have some more missions.

**Comment by litrax** [comment]
Shouldn't it rather be moved to backlog then hangin around in the QA pipeline?

**Comment by Hoegnison** [comment]
closed issue
